//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testgit_on_visualstudio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class htdata : DbContext
    {
        public htdata()
            : base("name=htdata")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_awards> tbl_awards { get; set; }
        public virtual DbSet<tbl_Research> tbl_Research { get; set; }
        public virtual DbSet<tbl_doctors> tbl_doctors { get; set; }
        public virtual DbSet<tbl_skills> tbl_skills { get; set; }
        public virtual DbSet<tbl_Patient> tbl_Patient { get; set; }
        public virtual DbSet<tbl_Visit> tbl_Visit { get; set; }
        public virtual DbSet<tbl_VisitType> tbl_VisitType { get; set; }
        public virtual DbSet<View_Visit> View_Visit { get; set; }
    }
}
